# Имя файла
TARGET = calculator

# Compilator
CXX = g++

#Flagi compilatora
CXXFLAGS = -Wall -02

#Cel raboty
all: $(Target)

#Pravilo dlya sborki
$(TARGET): calculator.cpp
	$(CXX) $(CXXFLAGS) -o $(TARGET) calculator.cpp

#clean
clean:
	rm -f $(TARGET)
